# ~/.bashrc: executed by bash(1) for interactive shells.

# User dependent .bashrc file

# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return


if [[ "$OSTYPE" == "linux-gnu" ]]; then
	echo "Detected linux - loading specific bashrc"
	source ~/.bashrc.linux
elif [[ "$OSTYPE" == "darwin"* ]]; then
	echo "Detected mac - loading specific bashrc"
	source ~/.bashrc.mac
elif [[ "$OSTYPE" == "cygwin" ]]; then
	echo "Detected cygwin - loading specific bashrc"
	source ~/.bashrc.cygwin
elif [[ "$OSTYPE" == "msys" ]]; then
	echo "Detected msys - loading specific bashrc"
	source ~/.bashrc.msys
elif [[ "$OSTYPE" == "win32" ]]; then
	echo "Detected win32 - loading specific bashrc"
	source ~/.bashrc.win32
elif [[ "$OSTYPE" == "freebsd"* ]]; then
	echo "Detected freebsd - loading specific bashrc"
	source ~/.bashrc.freebsd
else
	echo "Unknown OS - not loading specific bashrc"
fi

# Shell Options
# Make bash append rather than overwrite the history on disk
shopt -s histappend

# Completion options
# Uncomment to turn on programmable completion enhancements.
# Any completions you add in ~/.bash_completion are sourced last.
# [[ -f /etc/bash_completion ]] && . /etc/bash_completion

# History Options

# Aliases
if [ -f "${HOME}/.bash_aliases" ]; then
   source "${HOME}/.bash_aliases"
fi

# Umask
# Set a more restrictive umask: i.e. no exec perms for others:
# umask 027

# Functions
#
# Some people use a different file for functions
if [ -f "${HOME}/.bash_functions" ]; then
  source "${HOME}/.bash_functions"
fi

